# Generated by Django 2.0.1 on 2018-01-05 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_auto_20180104_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_subject', models.CharField(choices=[('1', 'Multiplication'), ('2', 'Division'), ('3', 'Spanish Vocab'), ('4', 'Mandarin Vocab'), ('5', 'English Grammar'), ('6', 'Programming')], default='1', max_length=50)),
                ('answer1', models.IntegerField(default='0')),
                ('answer2', models.IntegerField(default='0')),
                ('answer3', models.IntegerField(default='0')),
                ('answer4', models.IntegerField(default='0')),
                ('raw_answer', models.CharField(choices=[('1', models.IntegerField(default='0')), ('2', models.IntegerField(default='0')), ('3', models.IntegerField(default='0')), ('4', models.IntegerField(default='0'))], default='1', max_length=50)),
                ('was_correct', models.BooleanField()),
                ('question', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
        ),
    ]
